// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protos/oauth_client/oauth_authorize_params.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OauthAuthorizeUrlParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RedirectUri  string `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Scope        string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	ResponseType string `protobuf:"bytes,3,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	State        string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Relogin      bool   `protobuf:"varint,5,opt,name=relogin,proto3" json:"relogin,omitempty"`
	Drive        string `protobuf:"bytes,6,opt,name=drive,proto3" json:"drive,omitempty"`
}

func (x *OauthAuthorizeUrlParams) Reset() {
	*x = OauthAuthorizeUrlParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_oauth_client_oauth_authorize_params_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OauthAuthorizeUrlParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthAuthorizeUrlParams) ProtoMessage() {}

func (x *OauthAuthorizeUrlParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_oauth_client_oauth_authorize_params_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthAuthorizeUrlParams.ProtoReflect.Descriptor instead.
func (*OauthAuthorizeUrlParams) Descriptor() ([]byte, []int) {
	return file_protos_oauth_client_oauth_authorize_params_proto_rawDescGZIP(), []int{0}
}

func (x *OauthAuthorizeUrlParams) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *OauthAuthorizeUrlParams) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OauthAuthorizeUrlParams) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *OauthAuthorizeUrlParams) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OauthAuthorizeUrlParams) GetRelogin() bool {
	if x != nil {
		return x.Relogin
	}
	return false
}

func (x *OauthAuthorizeUrlParams) GetDrive() string {
	if x != nil {
		return x.Drive
	}
	return ""
}

var File_protos_oauth_client_oauth_authorize_params_proto protoreflect.FileDescriptor

var file_protos_oauth_client_oauth_authorize_params_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbd, 0x01, 0x0a, 0x17, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x72, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72,
	0x69, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x42, 0x16, 0x5a, 0x14, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_oauth_client_oauth_authorize_params_proto_rawDescOnce sync.Once
	file_protos_oauth_client_oauth_authorize_params_proto_rawDescData = file_protos_oauth_client_oauth_authorize_params_proto_rawDesc
)

func file_protos_oauth_client_oauth_authorize_params_proto_rawDescGZIP() []byte {
	file_protos_oauth_client_oauth_authorize_params_proto_rawDescOnce.Do(func() {
		file_protos_oauth_client_oauth_authorize_params_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_oauth_client_oauth_authorize_params_proto_rawDescData)
	})
	return file_protos_oauth_client_oauth_authorize_params_proto_rawDescData
}

var file_protos_oauth_client_oauth_authorize_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_oauth_client_oauth_authorize_params_proto_goTypes = []interface{}{
	(*OauthAuthorizeUrlParams)(nil), // 0: OauthAuthorizeUrlParams
}
var file_protos_oauth_client_oauth_authorize_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_oauth_client_oauth_authorize_params_proto_init() }
func file_protos_oauth_client_oauth_authorize_params_proto_init() {
	if File_protos_oauth_client_oauth_authorize_params_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_oauth_client_oauth_authorize_params_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OauthAuthorizeUrlParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_oauth_client_oauth_authorize_params_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_oauth_client_oauth_authorize_params_proto_goTypes,
		DependencyIndexes: file_protos_oauth_client_oauth_authorize_params_proto_depIdxs,
		MessageInfos:      file_protos_oauth_client_oauth_authorize_params_proto_msgTypes,
	}.Build()
	File_protos_oauth_client_oauth_authorize_params_proto = out.File
	file_protos_oauth_client_oauth_authorize_params_proto_rawDesc = nil
	file_protos_oauth_client_oauth_authorize_params_proto_goTypes = nil
	file_protos_oauth_client_oauth_authorize_params_proto_depIdxs = nil
}
