// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protos/adrive_client/adrive_open_file_batch_get_params.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdriveOpenFileBatchGetParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileList            []*BatchGetFileItem `protobuf:"bytes,1,rep,name=file_list,json=fileList,proto3" json:"file_list,omitempty"`
	VideoThumbnailTime  int64               `protobuf:"varint,2,opt,name=video_thumbnail_time,json=videoThumbnailTime,proto3" json:"video_thumbnail_time,omitempty"`
	VideoThumbnailWidth int64               `protobuf:"varint,3,opt,name=video_thumbnail_width,json=videoThumbnailWidth,proto3" json:"video_thumbnail_width,omitempty"`
	ImageThumbnailWidth int64               `protobuf:"varint,4,opt,name=image_thumbnail_width,json=imageThumbnailWidth,proto3" json:"image_thumbnail_width,omitempty"`
}

func (x *AdriveOpenFileBatchGetParams) Reset() {
	*x = AdriveOpenFileBatchGetParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_adrive_client_adrive_open_file_batch_get_params_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdriveOpenFileBatchGetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdriveOpenFileBatchGetParams) ProtoMessage() {}

func (x *AdriveOpenFileBatchGetParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_adrive_client_adrive_open_file_batch_get_params_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdriveOpenFileBatchGetParams.ProtoReflect.Descriptor instead.
func (*AdriveOpenFileBatchGetParams) Descriptor() ([]byte, []int) {
	return file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescGZIP(), []int{0}
}

func (x *AdriveOpenFileBatchGetParams) GetFileList() []*BatchGetFileItem {
	if x != nil {
		return x.FileList
	}
	return nil
}

func (x *AdriveOpenFileBatchGetParams) GetVideoThumbnailTime() int64 {
	if x != nil {
		return x.VideoThumbnailTime
	}
	return 0
}

func (x *AdriveOpenFileBatchGetParams) GetVideoThumbnailWidth() int64 {
	if x != nil {
		return x.VideoThumbnailWidth
	}
	return 0
}

func (x *AdriveOpenFileBatchGetParams) GetImageThumbnailWidth() int64 {
	if x != nil {
		return x.ImageThumbnailWidth
	}
	return 0
}

type BatchGetFileItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriveId string `protobuf:"bytes,1,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	FileId  string `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *BatchGetFileItem) Reset() {
	*x = BatchGetFileItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_adrive_client_adrive_open_file_batch_get_params_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFileItem) ProtoMessage() {}

func (x *BatchGetFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_adrive_client_adrive_open_file_batch_get_params_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFileItem.ProtoReflect.Descriptor instead.
func (*BatchGetFileItem) Descriptor() ([]byte, []int) {
	return file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescGZIP(), []int{1}
}

func (x *BatchGetFileItem) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *BatchGetFileItem) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

var File_protos_adrive_client_adrive_open_file_batch_get_params_proto protoreflect.FileDescriptor

var file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x6f, 0x70,
	0x65, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x67, 0x65,
	0x74, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8,
	0x01, 0x0a, 0x1c, 0x41, 0x64, 0x72, 0x69, 0x76, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c,
	0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x2e, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x30, 0x0a, 0x14, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x32, 0x0a, 0x15, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x13, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x32, 0x0a, 0x15, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x22, 0x46, 0x0a, 0x10, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x0a,
	0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x72, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x64, 0x42, 0x17, 0x5a, 0x15, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescOnce sync.Once
	file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescData = file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDesc
)

func file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescGZIP() []byte {
	file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescOnce.Do(func() {
		file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescData)
	})
	return file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDescData
}

var file_protos_adrive_client_adrive_open_file_batch_get_params_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_adrive_client_adrive_open_file_batch_get_params_proto_goTypes = []interface{}{
	(*AdriveOpenFileBatchGetParams)(nil), // 0: AdriveOpenFileBatchGetParams
	(*BatchGetFileItem)(nil),             // 1: BatchGetFileItem
}
var file_protos_adrive_client_adrive_open_file_batch_get_params_proto_depIdxs = []int32{
	1, // 0: AdriveOpenFileBatchGetParams.file_list:type_name -> BatchGetFileItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_adrive_client_adrive_open_file_batch_get_params_proto_init() }
func file_protos_adrive_client_adrive_open_file_batch_get_params_proto_init() {
	if File_protos_adrive_client_adrive_open_file_batch_get_params_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_adrive_client_adrive_open_file_batch_get_params_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdriveOpenFileBatchGetParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_adrive_client_adrive_open_file_batch_get_params_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetFileItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_adrive_client_adrive_open_file_batch_get_params_proto_goTypes,
		DependencyIndexes: file_protos_adrive_client_adrive_open_file_batch_get_params_proto_depIdxs,
		MessageInfos:      file_protos_adrive_client_adrive_open_file_batch_get_params_proto_msgTypes,
	}.Build()
	File_protos_adrive_client_adrive_open_file_batch_get_params_proto = out.File
	file_protos_adrive_client_adrive_open_file_batch_get_params_proto_rawDesc = nil
	file_protos_adrive_client_adrive_open_file_batch_get_params_proto_goTypes = nil
	file_protos_adrive_client_adrive_open_file_batch_get_params_proto_depIdxs = nil
}
