// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protos/adrive_client/adrive_user_get_drive_info.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdriveUserGetDriveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar          string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	DefaultDriveId  string `protobuf:"bytes,4,opt,name=default_drive_id,json=defaultDriveId,proto3" json:"default_drive_id,omitempty"`
	ResourceDriveId string `protobuf:"bytes,5,opt,name=resource_drive_id,json=resourceDriveId,proto3" json:"resource_drive_id,omitempty"`
	BackupDriveId   string `protobuf:"bytes,6,opt,name=backup_drive_id,json=backupDriveId,proto3" json:"backup_drive_id,omitempty"`
}

func (x *AdriveUserGetDriveInfo) Reset() {
	*x = AdriveUserGetDriveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_adrive_client_adrive_user_get_drive_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdriveUserGetDriveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdriveUserGetDriveInfo) ProtoMessage() {}

func (x *AdriveUserGetDriveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_adrive_client_adrive_user_get_drive_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdriveUserGetDriveInfo.ProtoReflect.Descriptor instead.
func (*AdriveUserGetDriveInfo) Descriptor() ([]byte, []int) {
	return file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDescGZIP(), []int{0}
}

func (x *AdriveUserGetDriveInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdriveUserGetDriveInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdriveUserGetDriveInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdriveUserGetDriveInfo) GetDefaultDriveId() string {
	if x != nil {
		return x.DefaultDriveId
	}
	return ""
}

func (x *AdriveUserGetDriveInfo) GetResourceDriveId() string {
	if x != nil {
		return x.ResourceDriveId
	}
	return ""
}

func (x *AdriveUserGetDriveInfo) GetBackupDriveId() string {
	if x != nil {
		return x.BackupDriveId
	}
	return ""
}

var File_protos_adrive_client_adrive_user_get_drive_info_proto protoreflect.FileDescriptor

var file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDesc = []byte{
	0x0a, 0x35, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x28, 0x0a, 0x10, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x5f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x49,
	0x64, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x49, 0x64, 0x42, 0x17, 0x5a, 0x15, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDescOnce sync.Once
	file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDescData = file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDesc
)

func file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDescGZIP() []byte {
	file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDescOnce.Do(func() {
		file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDescData)
	})
	return file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDescData
}

var file_protos_adrive_client_adrive_user_get_drive_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_adrive_client_adrive_user_get_drive_info_proto_goTypes = []interface{}{
	(*AdriveUserGetDriveInfo)(nil), // 0: AdriveUserGetDriveInfo
}
var file_protos_adrive_client_adrive_user_get_drive_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_adrive_client_adrive_user_get_drive_info_proto_init() }
func file_protos_adrive_client_adrive_user_get_drive_info_proto_init() {
	if File_protos_adrive_client_adrive_user_get_drive_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_adrive_client_adrive_user_get_drive_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdriveUserGetDriveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_adrive_client_adrive_user_get_drive_info_proto_goTypes,
		DependencyIndexes: file_protos_adrive_client_adrive_user_get_drive_info_proto_depIdxs,
		MessageInfos:      file_protos_adrive_client_adrive_user_get_drive_info_proto_msgTypes,
	}.Build()
	File_protos_adrive_client_adrive_user_get_drive_info_proto = out.File
	file_protos_adrive_client_adrive_user_get_drive_info_proto_rawDesc = nil
	file_protos_adrive_client_adrive_user_get_drive_info_proto_goTypes = nil
	file_protos_adrive_client_adrive_user_get_drive_info_proto_depIdxs = nil
}
