// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protos/adrive_client/adrive_open_file_list_prams.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdriveOpenFileListParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriveId             string `protobuf:"bytes,1,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	Limit               int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Marker              string `protobuf:"bytes,3,opt,name=marker,proto3" json:"marker,omitempty"`
	OrderBy             string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	OrderDirection      string `protobuf:"bytes,5,opt,name=order_direction,json=orderDirection,proto3" json:"order_direction,omitempty"`
	ParentFileId        string `protobuf:"bytes,6,opt,name=parent_file_id,json=parentFileId,proto3" json:"parent_file_id,omitempty"`
	Category            string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Type                string `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	VideoThumbnailTime  int64  `protobuf:"varint,9,opt,name=video_thumbnail_time,json=videoThumbnailTime,proto3" json:"video_thumbnail_time,omitempty"`
	VideoThumbnailWidth int64  `protobuf:"varint,10,opt,name=video_thumbnail_width,json=videoThumbnailWidth,proto3" json:"video_thumbnail_width,omitempty"`
	ImageThumbnailWidth int64  `protobuf:"varint,11,opt,name=image_thumbnail_width,json=imageThumbnailWidth,proto3" json:"image_thumbnail_width,omitempty"`
	Fields              string `protobuf:"bytes,12,opt,name=fields,proto3" json:"fields,omitempty"`
}

func (x *AdriveOpenFileListParams) Reset() {
	*x = AdriveOpenFileListParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_adrive_client_adrive_open_file_list_prams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdriveOpenFileListParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdriveOpenFileListParams) ProtoMessage() {}

func (x *AdriveOpenFileListParams) ProtoReflect() protoreflect.Message {
	mi := &file_protos_adrive_client_adrive_open_file_list_prams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdriveOpenFileListParams.ProtoReflect.Descriptor instead.
func (*AdriveOpenFileListParams) Descriptor() ([]byte, []int) {
	return file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDescGZIP(), []int{0}
}

func (x *AdriveOpenFileListParams) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *AdriveOpenFileListParams) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdriveOpenFileListParams) GetMarker() string {
	if x != nil {
		return x.Marker
	}
	return ""
}

func (x *AdriveOpenFileListParams) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *AdriveOpenFileListParams) GetOrderDirection() string {
	if x != nil {
		return x.OrderDirection
	}
	return ""
}

func (x *AdriveOpenFileListParams) GetParentFileId() string {
	if x != nil {
		return x.ParentFileId
	}
	return ""
}

func (x *AdriveOpenFileListParams) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AdriveOpenFileListParams) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AdriveOpenFileListParams) GetVideoThumbnailTime() int64 {
	if x != nil {
		return x.VideoThumbnailTime
	}
	return 0
}

func (x *AdriveOpenFileListParams) GetVideoThumbnailWidth() int64 {
	if x != nil {
		return x.VideoThumbnailWidth
	}
	return 0
}

func (x *AdriveOpenFileListParams) GetImageThumbnailWidth() int64 {
	if x != nil {
		return x.ImageThumbnailWidth
	}
	return 0
}

func (x *AdriveOpenFileListParams) GetFields() string {
	if x != nil {
		return x.Fields
	}
	return ""
}

var File_protos_adrive_client_adrive_open_file_list_prams_proto protoreflect.FileDescriptor

var file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDesc = []byte{
	0x0a, 0x36, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x6f, 0x70,
	0x65, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x61,
	0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x03, 0x0a, 0x18, 0x41, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x72, 0x69, 0x76, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x5f, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x32,
	0x0a, 0x15, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x42, 0x17, 0x5a, 0x15, 0x61, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDescOnce sync.Once
	file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDescData = file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDesc
)

func file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDescGZIP() []byte {
	file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDescOnce.Do(func() {
		file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDescData)
	})
	return file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDescData
}

var file_protos_adrive_client_adrive_open_file_list_prams_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_adrive_client_adrive_open_file_list_prams_proto_goTypes = []interface{}{
	(*AdriveOpenFileListParams)(nil), // 0: AdriveOpenFileListParams
}
var file_protos_adrive_client_adrive_open_file_list_prams_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_adrive_client_adrive_open_file_list_prams_proto_init() }
func file_protos_adrive_client_adrive_open_file_list_prams_proto_init() {
	if File_protos_adrive_client_adrive_open_file_list_prams_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_adrive_client_adrive_open_file_list_prams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdriveOpenFileListParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_adrive_client_adrive_open_file_list_prams_proto_goTypes,
		DependencyIndexes: file_protos_adrive_client_adrive_open_file_list_prams_proto_depIdxs,
		MessageInfos:      file_protos_adrive_client_adrive_open_file_list_prams_proto_msgTypes,
	}.Build()
	File_protos_adrive_client_adrive_open_file_list_prams_proto = out.File
	file_protos_adrive_client_adrive_open_file_list_prams_proto_rawDesc = nil
	file_protos_adrive_client_adrive_open_file_list_prams_proto_goTypes = nil
	file_protos_adrive_client_adrive_open_file_list_prams_proto_depIdxs = nil
}
