// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: protos/adrive_client/adrive_open_file_list_uploaded_parts.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdriveOpenFileListUploadedParts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriveId              string                    `protobuf:"bytes,1,opt,name=drive_id,json=driveId,proto3" json:"drive_id,omitempty"`
	UploadId             string                    `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	ParallelUpload       bool                      `protobuf:"varint,3,opt,name=parallel_upload,json=parallelUpload,proto3" json:"parallel_upload,omitempty"`
	UploadedParts        []*AdriveOpenFilePartInfo `protobuf:"bytes,4,rep,name=uploaded_parts,json=uploadedParts,proto3" json:"uploaded_parts,omitempty"`
	NextPartNumberMarker string                    `protobuf:"bytes,5,opt,name=next_part_number_marker,json=nextPartNumberMarker,proto3" json:"next_part_number_marker,omitempty"`
}

func (x *AdriveOpenFileListUploadedParts) Reset() {
	*x = AdriveOpenFileListUploadedParts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdriveOpenFileListUploadedParts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdriveOpenFileListUploadedParts) ProtoMessage() {}

func (x *AdriveOpenFileListUploadedParts) ProtoReflect() protoreflect.Message {
	mi := &file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdriveOpenFileListUploadedParts.ProtoReflect.Descriptor instead.
func (*AdriveOpenFileListUploadedParts) Descriptor() ([]byte, []int) {
	return file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDescGZIP(), []int{0}
}

func (x *AdriveOpenFileListUploadedParts) GetDriveId() string {
	if x != nil {
		return x.DriveId
	}
	return ""
}

func (x *AdriveOpenFileListUploadedParts) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *AdriveOpenFileListUploadedParts) GetParallelUpload() bool {
	if x != nil {
		return x.ParallelUpload
	}
	return false
}

func (x *AdriveOpenFileListUploadedParts) GetUploadedParts() []*AdriveOpenFilePartInfo {
	if x != nil {
		return x.UploadedParts
	}
	return nil
}

func (x *AdriveOpenFileListUploadedParts) GetNextPartNumberMarker() string {
	if x != nil {
		return x.NextPartNumberMarker
	}
	return ""
}

var File_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto protoreflect.FileDescriptor

var file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x6f, 0x70,
	0x65, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65,
	0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x6f,
	0x70, 0x65, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf9,
	0x01, 0x0a, 0x1f, 0x41, 0x64, 0x72, 0x69, 0x76, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61, 0x72,
	0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x72, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61,
	0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x3e, 0x0a, 0x0e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f,
	0x70, 0x61, 0x72, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x41, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x50, 0x61,
	0x72, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x17, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x42, 0x17, 0x5a, 0x15, 0x61, 0x64,
	0x72, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDescOnce sync.Once
	file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDescData = file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDesc
)

func file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDescGZIP() []byte {
	file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDescOnce.Do(func() {
		file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDescData)
	})
	return file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDescData
}

var file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_goTypes = []interface{}{
	(*AdriveOpenFileListUploadedParts)(nil), // 0: AdriveOpenFileListUploadedParts
	(*AdriveOpenFilePartInfo)(nil),          // 1: AdriveOpenFilePartInfo
}
var file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_depIdxs = []int32{
	1, // 0: AdriveOpenFileListUploadedParts.uploaded_parts:type_name -> AdriveOpenFilePartInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_init() }
func file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_init() {
	if File_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto != nil {
		return
	}
	file_protos_adrive_client_adrive_open_file_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdriveOpenFileListUploadedParts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_goTypes,
		DependencyIndexes: file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_depIdxs,
		MessageInfos:      file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_msgTypes,
	}.Build()
	File_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto = out.File
	file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_rawDesc = nil
	file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_goTypes = nil
	file_protos_adrive_client_adrive_open_file_list_uploaded_parts_proto_depIdxs = nil
}
